services:
  backend-oliver:
    image: node:20-alpine
    working_dir: /data
    volumes:
      - .:/data
    ports:
      - "3000:3000"
    command: npx -y json-server db.json --host 0.0.0.0 --port 3000

  app-oliver:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend-oliver